# Generated by Django 5.2.6 on 2025-09-14 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hs_apertura', models.DateTimeField()),
                ('fecha_hs_cierre', models.DateTimeField(blank=True, null=True)),
                ('saldo_inicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tipo_movimiento', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_prod', models.CharField(max_length=50)),
                ('descripcion_prod', models.CharField(blank=True, max_length=100)),
                ('categoria_prod', models.CharField(max_length=50)),
                ('precio_prod', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_prod', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_prov', models.CharField(max_length=50)),
                ('tipo_prov', models.CharField(max_length=50)),
                ('telefono_prov', models.IntegerField(blank=True, null=True)),
                ('correo_prov', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion_prov', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_emp', models.CharField(max_length=50)),
                ('apellido_emp', models.CharField(max_length=50)),
                ('dni_emp', models.IntegerField(unique=True)),
                ('telefono_emp', models.IntegerField(blank=True, null=True)),
                ('domicilio_emp', models.CharField(max_length=50)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MiApp.caja')),
            ],
        ),
        migrations.CreateModel(
            name='ProvProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_prov_prod', models.CharField(max_length=50)),
                ('descripcion_prov_prod', models.TextField(blank=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MiApp.producto')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MiApp.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_venta', models.DateTimeField()),
                ('total_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado_venta', models.CharField(max_length=50)),
                ('tipo_pago_venta', models.CharField(max_length=50)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MiApp.caja')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_venta', models.IntegerField()),
                ('precio_uni_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('productos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MiApp.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MiApp.venta')),
            ],
        ),
        migrations.CreateModel(
            name='VentaSaeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_saeta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago_saeta', models.DateField()),
                ('porcentaje_ganancia_saeta', models.DecimalField(decimal_places=2, max_digits=5)),
                ('detalle_ventas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MiApp.detalleventa')),
            ],
        ),
    ]
