# Generated by Django 5.2.6 on 2025-10-08 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiApp', '0002_rename_productos_detalleventa_producto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provproducto',
            name='descripcion_prov_prod',
        ),
        migrations.RemoveField(
            model_name='provproducto',
            name='nombre_prov_prod',
        ),
        migrations.AddField(
            model_name='producto',
            name='proveedores',
            field=models.ManyToManyField(through='MiApp.ProvProducto', to='MiApp.proveedor'),
        ),
    ]
