# Generated by Django 5.2.6 on 2025-10-13 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiApp', '0004_alter_provproducto_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='telefono_prov',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
