# Generated by Django 5.2.6 on 2025-11-19 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_prod', models.CharField(max_length=100)),
                ('categoria_prod', models.CharField(max_length=50)),
                ('descripcion_prod', models.TextField(blank=True, null=True)),
                ('codigo_prod', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('precio_venta', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cantidad', models.IntegerField(default=0, verbose_name='Stock disponible')),
                ('stock_minimo', models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_prov', models.CharField(max_length=50, unique=True)),
                ('tipo_prov', models.CharField(max_length=50)),
                ('telefono_prov', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('correo_prov', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('direccion_prov', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('dni_proveedor', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_emp', models.CharField(blank=True, max_length=50, null=True)),
                ('apellido_emp', models.CharField(blank=True, max_length=50, null=True)),
                ('dni_emp', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('telefono_emp', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('domicilio_emp', models.TextField(blank=True, null=True)),
                ('tipo_usuario', models.CharField(choices=[('jefa', 'Jefa/Encargada'), ('empleada', 'Empleada')], default='empleada', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hs_apertura', models.DateTimeField()),
                ('fecha_hs_cierre', models.DateTimeField(blank=True, null=True)),
                ('saldo_inicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ingresos', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ingresos extra')),
                ('egresos', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Egresos')),
                ('monto_contado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto contado')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('turno', models.CharField(choices=[('mañana', 'Turno Mañana'), ('tarde', 'Turno Tarde')], default='mañana', max_length=20)),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('cerrada', 'Cerrada')], default='abierta', max_length=20)),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='MiApp.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_compra', models.CharField(max_length=50, unique=True)),
                ('fecha_compra', models.DateField(auto_now_add=True)),
                ('cantidad', models.IntegerField()),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('anulada', 'Anulada')], default='activa', max_length=20)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MiApp.producto')),
                ('proveedores', models.ManyToManyField(blank=True, to='MiApp.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_venta', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Código de Venta')),
                ('fecha_hora_venta', models.DateTimeField(auto_now_add=True)),
                ('total_venta', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado_venta', models.CharField(choices=[('pendiente', 'Pendiente'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='completada', max_length=20)),
                ('tipo_pago_venta', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia')], default='efectivo', max_length=20)),
                ('monto_recibido', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('vuelto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MiApp.caja')),
            ],
            options={
                'ordering': ['-fecha_hora_venta'],
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='MiApp.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='MiApp.venta')),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalles de Ventas',
            },
        ),
        migrations.CreateModel(
            name='VentaSaeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_saeta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago_saeta', models.DateField()),
                ('porcentaje_ganancia_saeta', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ganancia_drugstore', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('detalle_venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MiApp.detalleventa')),
                ('venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MiApp.venta')),
            ],
        ),
        migrations.AddConstraint(
            model_name='empleado',
            constraint=models.UniqueConstraint(fields=('nombre_emp', 'apellido_emp'), name='unique_nombre_apellido_empleado'),
        ),
    ]
