# Generated by Django 5.2.6 on 2025-10-08 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalleventa',
            old_name='productos',
            new_name='producto',
        ),
        migrations.RenameField(
            model_name='ventasaeta',
            old_name='detalle_ventas',
            new_name='detalle_venta',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='stock_prod',
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_actual',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_minimo',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion_prod',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre_prod',
            field=models.CharField(max_length=100),
        ),
    ]
