# Generated by Django 5.2.6 on 2025-11-02 15:40

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='activo',
            new_name='estado',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='codigo_barras',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precio_compra',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='stock_actual',
        ),
        migrations.AddField(
            model_name='compra',
            name='categoria_prod',
            field=models.CharField(default='General', max_length=50, verbose_name='Categoría'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='cantidad',
            field=models.IntegerField(default=0, verbose_name='Cantidad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='codigo_prod',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Código'),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_entrada',
            field=models.DateField(default=datetime.date(2025, 11, 2), verbose_name='Fecha entrada'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha vencimiento'),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio total'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='cantidad',
            field=models.IntegerField(verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='codigo_compra',
            field=models.CharField(default=uuid.uuid4, max_length=20, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='fecha_entrada',
            field=models.DateField(verbose_name='Fecha entrada'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha vencimiento'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='precio_total',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio total'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio venta'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio venta'),
        ),
    ]
