# Generated by Django 5.2.6 on 2025-11-20 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MiApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedor',
            old_name='dni_proveedor',
            new_name='codigo_proveedor',
        ),
    ]
