# Generated by Django 5.2.6 on 2025-11-21 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MiApp', '0002_producto_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='estado',
        ),
    ]
