# Generated by Django 5.2.6 on 2025-11-02 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiApp', '0002_rename_activo_producto_estado_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compra',
            options={},
        ),
        migrations.RemoveField(
            model_name='compra',
            name='proveedor',
        ),
        migrations.AddField(
            model_name='compra',
            name='proveedores',
            field=models.ManyToManyField(to='MiApp.proveedor'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='cantidad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='compra',
            name='categoria_prod',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='compra',
            name='codigo_compra',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='compra',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compra',
            name='fecha_entrada',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='compra',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compra',
            name='precio_total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='compra',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='compra',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MiApp.producto'),
        ),
    ]
