# Generated by Django 5.2.6 on 2025-11-20 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MiApp', '0003_producto_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='estado',
        ),
    ]
