# Generated by Django 5.2.6 on 2025-11-02 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiApp', '0003_alter_compra_options_remove_compra_proveedor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
