# Generated by Django 5.2.6 on 2025-10-08 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MiApp', '0003_remove_provproducto_descripcion_prov_prod_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='provproducto',
            unique_together={('producto', 'proveedor')},
        ),
    ]
