# Generated by Django 5.2.6 on 2025-11-02 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MiApp', '0004_proveedor_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='estado',
        ),
    ]
