# Generated by Django 5.2.6 on 2025-11-03 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MiApp', '0005_remove_producto_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='stock_minimo',
        ),
    ]
