# Generated by Django 5.2.6 on 2025-11-03 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiApp', '0006_remove_producto_stock_minimo'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock_actual',
            field=models.IntegerField(default=0, verbose_name='Stock actual'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='cantidad',
            field=models.IntegerField(default=0, verbose_name='Cantidad'),
        ),
    ]
