# Generated by Django 5.2.6 on 2025-10-27 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MiApp', '0006_turno_remove_caja_tipo_movimiento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='tipo_usuario',
        ),
    ]
