# Generated by Django 5.2.6 on 2025-10-27 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiApp', '0007_remove_empleado_tipo_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='tipo_usuario',
            field=models.CharField(choices=[('jefa', 'Jefa/Encargada'), ('empleada', 'Empleada')], default='empleada', max_length=10),
        ),
    ]
