# Generated by Django 5.2.6 on 2025-11-03 21:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiApp', '0007_producto_stock_actual_alter_producto_cantidad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalleventa',
            options={'verbose_name': 'Detalle de Venta', 'verbose_name_plural': 'Detalles de Ventas'},
        ),
        migrations.RenameField(
            model_name='detalleventa',
            old_name='precio_uni_venta',
            new_name='precio_unitario',
        ),
        migrations.RenameField(
            model_name='detalleventa',
            old_name='subtotal_venta',
            new_name='subtotal',
        ),
        migrations.RemoveField(
            model_name='detalleventa',
            name='cantidad_venta',
        ),
        migrations.RemoveField(
            model_name='detalleventa',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venta',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='caja',
            name='turno',
            field=models.CharField(choices=[('mañana', 'Turno Mañana'), ('tarde', 'Turno Tarde')], default='mañana', max_length=20),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='MiApp.venta'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='estado_venta',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='completada', max_length=20),
        ),
        migrations.AlterField(
            model_name='venta',
            name='monto_recibido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='venta',
            name='tipo_pago_venta',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia')], default='efectivo', max_length=20),
        ),
        migrations.AlterField(
            model_name='venta',
            name='total_venta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='venta',
            name='vuelto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
