# Generated by Django 5.2.6 on 2025-11-04 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiApp', '0008_alter_detalleventa_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='stock_actual',
        ),
        migrations.AlterField(
            model_name='producto',
            name='cantidad',
            field=models.IntegerField(default=0, verbose_name='Stock disponible'),
        ),
    ]
