# Generated by Django 5.2.6 on 2025-10-27 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MiApp', '0008_empleado_tipo_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='tipo_usuario',
        ),
    ]
