# Generated by Django 5.2.6 on 2025-11-04 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiApp', '0009_remove_producto_stock_actual_alter_producto_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventasaeta',
            name='detalle_venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MiApp.detalleventa'),
        ),
    ]
