# Generated by Django 5.2.6 on 2025-11-05 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiApp', '0010_alter_ventasaeta_detalle_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventasaeta',
            name='venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MiApp.venta'),
        ),
    ]
