# Generated by Django 5.2.6 on 2025-11-05 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiApp', '0012_alter_detalleventa_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='egresos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Egresos'),
        ),
        migrations.AddField(
            model_name='caja',
            name='ingresos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ingresos extra'),
        ),
        migrations.AddField(
            model_name='caja',
            name='monto_contado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto contado'),
        ),
    ]
