# Generated by Django 5.2.6 on 2025-11-05 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiApp', '0013_caja_egresos_caja_ingresos_caja_monto_contado'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventasaeta',
            name='ganancia_drugstore',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
