# Generated by Django 5.2.6 on 2025-11-13 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiApp', '0014_ventasaeta_ganancia_drugstore'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venta',
            options={'ordering': ['-fecha_hora_venta']},
        ),
        migrations.AddField(
            model_name='venta',
            name='codigo_venta',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Código de Venta'),
        ),
    ]
