# Generated by Django 5.2.6 on 2025-11-17 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiApp', '0015_alter_venta_options_venta_codigo_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='dni_proveedor',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
