# Generated by Django 5.2.6 on 2025-11-17 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiApp', '0016_proveedor_dni_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='dni_proveedor',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
