# Generated by Django 5.2.6 on 2025-11-17 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiApp', '0017_alter_proveedor_dni_proveedor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proveedor',
            options={'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='correo_prov',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='direccion_prov',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre_prov',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono_prov',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
