# Generated by Django 5.2.6 on 2025-11-18 04:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiApp', '0018_alter_proveedor_options_alter_proveedor_correo_prov_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='telefono_emp',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name='empleado',
            constraint=models.UniqueConstraint(fields=('nombre_emp', 'apellido_emp'), name='unique_nombre_apellido_empleado'),
        ),
    ]
