# Generated by Django 5.2.6 on 2025-11-18 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiApp', '0019_alter_empleado_telefono_emp_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compra',
            options={'ordering': ['-fecha_entrada']},
        ),
        migrations.RemoveField(
            model_name='compra',
            name='categoria_prod',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='fecha_actualizacion',
        ),
        migrations.AddField(
            model_name='compra',
            name='lote',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
