# Generated by Django 5.2.6 on 2025-11-18 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiApp', '0020_alter_compra_options_remove_compra_categoria_prod_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='categoria_prod',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
