# Generated by Django 5.2.6 on 2025-11-19 00:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiApp', '0021_compra_categoria_prod'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compra',
            options={},
        ),
        migrations.RemoveField(
            model_name='compra',
            name='categoria_prod',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='fecha_entrada',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='fecha_vencimiento',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='lote',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='precio_venta',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='fecha_entrada',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='fecha_vencimiento',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precio_total',
        ),
        migrations.AddField(
            model_name='compra',
            name='fecha_compra',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_minimo',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='compra',
            name='precio_total',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio total'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='proveedores',
            field=models.ManyToManyField(blank=True, to='MiApp.proveedor'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigo_prod',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
