# Generated by Django 5.2.6 on 2025-11-19 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiApp', '0022_alter_compra_options_remove_compra_categoria_prod_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='estado',
            field=models.CharField(choices=[('registrada', 'Registrada'), ('anulada', 'Anulada')], default='registrada', max_length=20),
        ),
        migrations.AlterField(
            model_name='compra',
            name='precio_total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
