# Generated by Django 5.2.6 on 2025-11-19 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiApp', '0023_compra_estado_alter_compra_precio_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='estado',
            field=models.CharField(choices=[('activa', 'Activa'), ('anulada', 'Anulada')], default='registrada', max_length=20),
        ),
    ]
