# Generated by Django 5.2.6 on 2025-11-19 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiApp', '0024_alter_compra_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='estado',
            field=models.CharField(choices=[('activa', 'Activa'), ('anulada', 'Anulada')], default='activa', max_length=20),
        ),
    ]
